#!/usr/bin/env bash
# Install (or update) the skills-maintain crontab entry.
# Usage:
#   ./scripts/cron/install.sh
#   ./scripts/cron/install.sh --schedule '0 3 * * *' --repo /path/to/skills
#   ./scripts/cron/install.sh --dry-run
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

SCHEDULE="0 */6 * * *"
SKILLS_REPO="$REPO_ROOT"
PYTHON="/usr/bin/python3"
LOG_FILE="landing/maintain.log"
CRON_MARKER="# skills-framework-maintain"
DRY_RUN=0
SHOW_HELP=0

if [[ -f "${SCRIPT_DIR}/config.env" ]]; then
  # shellcheck disable=SC1091
  set -a
  # shellcheck source=/dev/null
  source "${SCRIPT_DIR}/config.env"
  set +a
fi

usage() {
  cat <<'EOF'
Install the skills-maintain cron job.

Options:
  --repo PATH         Absolute path to skills repo (default: auto-detect)
  --schedule EXPR     Crontab schedule (default: 0 */6 * * *)
  --python PATH       Python interpreter (default: /usr/bin/python3)
  --log PATH          Log file relative to repo or absolute
  --dry-run           Print the crontab line; do not install
  -h, --help          Show this help

Config file (optional): scripts/cron/config.env
  Copy from config.env.example and edit. Flags override the file.

Examples:
  ./scripts/cron/install.sh
  ./scripts/cron/install.sh --schedule '0 3 * * *'
  ./scripts/cron/install.sh --dry-run
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo)
      SKILLS_REPO="${2:?}"
      shift 2
      ;;
    --schedule)
      SCHEDULE="${2:?}"
      shift 2
      ;;
    --python)
      PYTHON="${2:?}"
      shift 2
      ;;
    --log)
      LOG_FILE="${2:?}"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      SHOW_HELP=1
      shift
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ "$SHOW_HELP" -eq 1 ]]; then
  usage
  exit 0
fi

# Resolve absolute repo path
SKILLS_REPO="$(cd "$SKILLS_REPO" && pwd)"
WRAPPER="${SCRIPT_DIR}/skills-maintain.sh"

if [[ ! -f "$WRAPPER" ]]; then
  echo "Missing wrapper: $WRAPPER" >&2
  exit 2
fi
chmod +x "$WRAPPER" "${SCRIPT_DIR}/install.sh" "${SCRIPT_DIR}/uninstall.sh" 2>/dev/null || true
chmod +x "${SKILLS_REPO}/bin/skills-maintain" "${SKILLS_REPO}/bin/skills-export" 2>/dev/null || true

if [[ ! -f "${SKILLS_REPO}/core/manifest.yaml" ]]; then
  echo "Not a skills repo (no core/manifest.yaml): $SKILLS_REPO" >&2
  exit 2
fi

# Persist effective config for the wrapper / future installs
# (skipped on dry-run so CI/preview does not write config.env)
if [[ "$DRY_RUN" -eq 0 ]]; then
  cat >"${SCRIPT_DIR}/config.env" <<EOF
# Generated by scripts/cron/install.sh — safe to edit
SKILLS_REPO=${SKILLS_REPO}
SCHEDULE=${SCHEDULE}
PYTHON=${PYTHON}
LOG_FILE=${LOG_FILE}
SHELL=/bin/bash
PATH=/usr/local/bin:/usr/bin:/bin
CRON_MARKER=${CRON_MARKER}
EOF
fi

CRON_LINE="${SCHEDULE} ${WRAPPER}"
BLOCK=$(cat <<EOF
${CRON_MARKER}
SHELL=/bin/bash
PATH=/usr/local/bin:/usr/bin:/bin
${CRON_LINE}
EOF
)

echo "Repo:     $SKILLS_REPO"
echo "Schedule: $SCHEDULE"
echo "Wrapper:  $WRAPPER"
echo "Log:      $LOG_FILE"
echo
echo "Crontab entry:"
echo "$BLOCK"
echo

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "(dry-run) not installing"
  exit 0
fi

if ! command -v crontab >/dev/null 2>&1; then
  echo "crontab command not found — config.env written; add the block above manually." >&2
  echo "Manual run:  $WRAPPER" >&2
  exit 2
fi

# Remove any previous marked block, then append
EXISTING="$(crontab -l 2>/dev/null || true)"
FILTERED="$(printf '%s\n' "$EXISTING" | awk -v m="$CRON_MARKER" '
  $0 == m { skip=1; next }
  skip && /^SHELL=/ { next }
  skip && /^PATH=/ { next }
  skip && /skills-maintain\.sh/ { skip=0; next }
  skip && NF==0 { next }
  { skip=0; print }
')"

{
  printf '%s\n' "$FILTERED" | sed '/^$/N;/^\n$/D'
  echo
  echo "$BLOCK"
  echo
} | crontab -

echo "Installed. Verify with: crontab -l"
echo "Manual run:  $WRAPPER"
echo "Uninstall:   ${SCRIPT_DIR}/uninstall.sh"
